### ISSUE TITLE
Which shapenet voxel dataset is used?

### ISSUE THREAD

**Issue by noamgat** [facebookresearch/meshrcnn#10]
In preprocess_shapenet.py, the file that is checked is 'model.presolid.binvox'. According to the shapenet documentation ( https://www.shapenet.org/download/shapenetcore ), these are not part of ShapeNetCore v1 or v2.

In R2N2's datasets, the models are called model.binvox.

Which dataset should we get for the shapenet voxelizations?

**Comment by gkioxari** [comment]
Hi @noamgat! The voxelizations of the shapenet models are distributed from the ShapeNet team. So you will have to register and request it. Within that directory, you will find the `model.presolid.binvox` models which are the result of the voxelization of the 3D meshes (voxels occupy the surface and interior of the model). 

There you will also find `model.binvox` which are also voxels of the 3D meshes but only corresponding to the surface of the model (and not the interior).

**Comment by noamgat** [comment]
Thanks! Was able to find it.
(If anyone reads it in the future, it is available as a separate zip file in the same directory as the ShapeNetCore.v1.zip, but is not linked to in the download website)

**Comment by jpainam** [comment]
@noamgat 
This is my content of `ShapeNetCore.v1` Where do you find the `model.presolid.binvox`?
Thank you
<img width="2977" alt="Screenshot 2023-05-28 at 11 47 45 AM" src="https://github.com/facebookresearch/meshrcnn/assets/1701705/d299a9f0-4552-4b13-874e-14a181e20ca8">
