### ISSUE TITLE
How is the K vector estimated in Pix3D splits files?

### ISSUE THREAD

**Issue by vadimkantorov** [facebookresearch/meshrcnn#101]
The original Pix3D (https://github.com/xingyuansun/pix3d#dataset) `pix3d.json` file has only:
* **trans_mat** - object's translation vector assuming camera at origin
* **rot_mat** - object rotation matrix assuming camera at origin
* **cam_position** - camera's translation vector assuming object at origin
* **focal_length** - estimated camera's focal length

How do you estimate the vectors **`"K"`** found in your produced splits (`pix3d_s1_train.json` etc)? Is it some `(focal_length, x0, y0)` values?

1. `K[1]` seems to be `image_width / 2`, `K[2]` seems to be `image_height / 2`, correct?

2. `K[0]` seems to be used as `focal_length`: https://github.com/facebookresearch/meshrcnn/blob/d582649dc7b5518061da2ed42f45386a94fdd2f2/meshrcnn/evaluation/pix3d_evaluation.py#L317-L325 but value of `K[0]` doesn't match the value of `focal_length` in original `pix3d.json`. I must be misunderstanding something here. I guess `K` is in pixel units, while original `focal_length` is in millimeters or some other world units? What is semantics of `K[0]`?

Thank you @gkioxari!

**Comment by gkioxari** [comment]
Check https://github.com/facebookresearch/meshrcnn/issues/8

**Comment by vadimkantorov** [comment]
Thank you! #8 answers my question!
