### ISSUE TITLE
[question] Why does compare_meshes(gt_mesh, gt_mesh) not return 100% match metrics?

### ISSUE THREAD

**Issue by vadimkantorov** [facebookresearch/meshrcnn#102]
During sanity check / fuguring out debugging of Pix3D evaluation code, I ran:
```python
compare_meshes(gt_mesh, gt_mesh, reduce=False)
# {'Chamfer-L2': tensor([0.0095]), 'NormalConsistency': tensor([0.8982]), 'AbsNormalConsistency': tensor([0.9093]), 'Precision@0.100000': tensor([87.8900]), 'Recall@0.100000': tensor([87.7100]), 'F1@0.100000': tensor([87.7999]), 'Precision@0.200000': tensor([99.9500]), 'Recall@0.200000': tensor([99.9400]), 'F1@0.200000': tensor([99.9450]), 'Precision@0.300000': tensor([100.]), 'Recall@0.300000': tensor([100.]), 'F1@0.300000': tensor([100.]), 'Precision@0.400000': tensor([100.]), 'Recall@0.400000': tensor([100.]), 'F1@0.400000': tensor([100.]), 'Precision@0.500000': tensor([100.]), 'Recall@0.500000': tensor([100.]), 'F1@0.500000': tensor([100.])}
```

The meshes obviously match exactly, so I wonder why not precision/recall metrics are 100%? Is it because of point sampling process?

Thank you!

**Comment by gkioxari** [comment]
Exactly. Each mesh is converted into a point cloud by sampling points on the surface of the mesh. Obviously, if we sampled exactly the same points on the two identical meshes then the metrics would return 100%. You can verify this if you passed the identical point coulds in the point cloud comparisons where `pred_points = gt_points` and `pred_normals = gt_normals`.

https://github.com/facebookresearch/meshrcnn/blob/d582649dc7b5518061da2ed42f45386a94fdd2f2/meshrcnn/utils/metrics.py#L83-L85

**Comment by vadimkantorov** [comment]
Thank you!
