### ISSUE TITLE
Augmentations used?

### ISSUE THREAD

**Issue by vadimkantorov** [facebookresearch/meshrcnn#103]
Do I understand correctly that default detectron2's augmentations are used, namely only hflip and resizes?

https://detectron2.readthedocs.io/en/latest/modules/data.html#detectron2.data.detection_utils.build_augmentation

**Comment by gkioxari** [comment]
There is two types of augmentations 

* Image Augmentations: These refer to the augmentations to the input image and and you are correct that we use horizontal flipping and image scaling at train time following detectron2
* Region Augmentations: In two stage detectors (like Mask R-CNN, Mesh R-CNN etc.), there are region augmentations that happen implicitly through the RoI predictions which are noisy during training. These happen by defaul while training the model.

**Comment by vadimkantorov** [comment]
Thank you @gkioxari for so fast response :)

**Comment by vadimkantorov** [comment]
So, is shortest side deterministically resized to 800, right? (according to https://detectron2.readthedocs.io/en/latest/modules/config.html)
