### ISSUE TITLE
Segmentation fault when running Demo

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [facebookresearch/meshrcnn#11]
When running the demo I run into an segmentation fault. I've tried both with self downloaded weights as well as the default remote weights. Other than that I don't see things I could change. 

Exact command I used:
```bash
python demo/demo.py \
--config-file configs/pix3d/meshrcnn_R50_FPN.yaml \
--input ../pf.jpg \
--output output_demo \
--onlyhighest meshrcnn_R50.pth
```

**Comment by gkioxari** [comment]
Hi @Baukebrenninkmeijer! I need more information to be able to help you. Could you provide details on your environment (PyTorch version, python version, OS, CUDA/cuDNN, NVCC, GPU type, gcc). Then can you also report whether you are able to run detectron2 and pytorch3d?

**Comment by gkioxari** [comment]
Hi @Baukebrenninkmeijer! If you figured this out or if your issue is not related to this codebase, could you close the issue?

**Comment by gkioxari** [comment]
Given there is no response I will close this issue. Please reopen it if you haven't figured it out.
