### ISSUE TITLE
Optimal 3D object file format for meshrcnn

### ISSUE THREAD

**Issue by jth389** [facebookresearch/meshrcnn#17]
Hello,

I hope this is the proper forum for this question, if not I am apologize in advance.

I am creating a 3D object reverse search engine and have been looking at Mesh R-CNN for this with PyTorch model tracing and potentially FAISS.

My question is, are there particular 3D file storage formats that are superior to others? e.g. I have a 3D scanner that can output various filetypes including OBJ and PLY; is there a benefit to one over the other?

I am correct in assuming that I could easily train Mesh R-CNN on my dataset of 3D objects as long as the models are clean with fixed mesh and stored in either PLY or OBJ format?

Thank you in advance

paulo

**Comment by gkioxari** [comment]
Hi @jth389! 

Mesh R-CNN and most models handling 3D meshes don't depend on a particular object file format. Mesh R-CNN handles data which consist of a set of vertices and a set of faces indexing into the vertices. Now, how you store and read 3D object data is irrelevant. In Mesh R-CNN, we deal with `.obj` files, as both ShapeNet and Pix3D store their models in this file format. We use the PyTorch3d [obj_io.py](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/io/obj_io.py) to read/write `obj` files. But they could have been in any data format and that would have been totally fine. 

Regarding `obj` vs. `ply`, I think the ply format is more general and allows the user to specify exactly the format in which the data is provided in the header of the file, which in turn means more flexibility. `obj` is more constrained in that aspect. PyTorch3D provides [ply_io.py](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/io/ply_io.py) to read from `ply` files as well. 

I hope this was helpful!

**Comment by gkioxari** [comment]
I will close this issue, as it is not pertinent to the codebase but I am happy to answer more questions!
