### ISSUE TITLE
Problem with anotations

### ISSUE THREAD

**Issue by zshyang** [facebookresearch/meshrcnn#19]
Hi,
I was thinking, do you support multiple objects? I know it is not your paper's point. But in reality, there are lots of multiple objects in an image. While I have checked the Pix3D dataset, all the ground truths only provided with one mask.
So if I provide more than one mask in my own dataset. Do you support this feature?
Best regards,
zshyang

**Comment by gkioxari** [comment]
Hi @zshyang. 
Mesh R-CNN supports multiple objects and in fact we make predictions for multiple objects detected in an input image. It is actually the point of our work to support multiple objects and make predictions for all detected objects in an end-to-end manner and in a single forward pass. [Here](https://docs.google.com/presentation/d/18yd22C2RCs_dACrRL01r1eqHq9FrGwPXQAokq6QqSjE/edit) we are showing the output of Mesh R-CNN on input images from Pix3D. You can run the demo code if you wish to visualize results on an image of your choice. 

Your question regarding annotations is mostly pertinent to the dataset. Pix3D has only one object annotated per image. For the dataset annotations, we adopt the COCO format (read [here](http://cocodataset.org/#format-data) for more info). This format can support arbitrary annotations per image. If you have your own dataset, you need to create a file with the COCO format guidelines and you might have to write your own data loading similar to [pix3d.py](https://github.com/facebookresearch/meshrcnn/blob/master/meshrcnn/data/datasets/pix3d.py).

**Comment by zshyang** [comment]
Hi @gkioxari ,
Thanks a lot for your reply. Your answer solved my problem.
