### ISSUE TITLE
Do not sure about what is the output.

### ISSUE THREAD

**Issue by zshyang** [facebookresearch/meshrcnn#20]
Hi,
Is the output mesh from the network is in camera space? Or in object space?
For camera space, I mean the output mesh's vertex (x, y, z) corresponds to the pixel position.
For object space, It means the object's canonical position.

**Comment by gkioxari** [comment]
Hi @zshyang! The output is in the camera coordinate system, which is what you refer as camera space!

**Comment by zshyang** [comment]
Hi @gkioxari , thanks a lot for your explanation!

**Comment by zshyang** [comment]
I have one more question regarding the mesh part. Where in your code you did the rotation and translation of the obj file?

**Comment by gkioxari** [comment]
@zshyang The data processing is happening at various locations. Initially, the data is loaded [here](https://github.com/facebookresearch/meshrcnn/blob/master/meshrcnn/data/datasets/pix3d.py), the roi specific data is computed [here](https://github.com/facebookresearch/meshrcnn/blob/master/meshrcnn/data/meshrcnn_transforms.py) and aligned to rois [here](https://github.com/facebookresearch/meshrcnn/blob/master/meshrcnn/modeling/roi_heads/mesh_head.py#L54) for meshes, and [here](https://github.com/facebookresearch/meshrcnn/blob/master/meshrcnn/modeling/roi_heads/voxel_head.py#L54) for voxels. 
As an advice, I understand that roi-based object recognition is a little complicated and the codebases are complex, and sometimes clarity is sacrificed for modularity, however I do urge you to devote some time to figure the data flow out for yourself as this will force you to understand the models much better.

**Comment by gkioxari** [comment]
@zshyang You haven't responded to this issue, so I am not sure whether your question has been addressed. I am closing this issue, and if you need to follow up please re-open it.

**Comment by zshyang** [comment]
Thanks a lot! You have solved my problem!

**Comment by ForeverRuri** [comment]
> Hi @zshyang! The output is in the camera coordinate system, which is what you refer as camera space!

Hi 
So u mean what i get from the network is the cords of verts and faces in the camera coordinate

right？

**Comment by ForeverRuri** [comment]
@gkioxari
