### ISSUE TITLE
Training with custom dataset.

### ISSUE THREAD

**Issue by zshyang** [facebookresearch/meshrcnn#24]
Hi, 
I tried with my dataset. And each image has multiple annotations. I provide the `COCO` format `json` file. But during the training I get the error said:
```
batch_crop_voels_within_box
     voxel_tensor = torch.stack(voxels.data, 0)
RuntimeError: invalid argument 0:
```
It seems that the error is because of the voxel data within the image have different size. 
So my question is how to use your code to train the network that is provided with data that have multiple objects in the images.
Best regards,
zshyang

**Comment by gkioxari** [comment]
Hi @zshyang! Unfortunately, I can't debug your code for obvious reasons :)
I do have some piece of advise on how to proceed though. I recommend putting a 

```
import pdb; pdb.set_trace()
```
before this commend and look into all the tensors. This will reveal a lot about your issues. 

I have also implemented a way to visualize your minibatches, that is the data is created during training. This flag is called `cfg.MODEL.VIS_MINIBATCH` which you can see in [L16](https://github.com/facebookresearch/meshrcnn/blob/master/meshrcnn/config/config.py#L16) in `config.py`. If you se this label to `True` (it's `False`) by default, then you will be able to visualize your minibatches, which is crucial when training models with complicated data. 

I hope that helps! Good luck :)

**Comment by zshyang** [comment]
Wow, thanks a lot! Your suggestion is amazing. I will try them.

**Comment by zshyang** [comment]
Hi @gkioxari ,
I could train the network for a few iterations and sometimes a few epochs. But suddenly the code crashed.
So my guess is that some data in my dataset does not fit well to the network. Is there any way to filter out these 'bad' data? For example, I could do not shuffle the data during training. And print the index of the dad data. I just do not know how to implement this in `detectron` structure. Would you provide me with some possible debugging ideas?
Best regards,
zshyang

**Comment by gkioxari** [comment]
Hi @zshyang! You don't provide any info for when your code crashes, eg error message, stacktrace etc. Without this info there is absolutely no way for me to know what is going on. I can't debug your code in any way. It's clear you need to debug your data. To do this you can experiment with a small subset of them (e.g. start with 1 data point in the training set only), or print relevant info in the data transforms file when the data is being processed. This is the extent to which I can help you without any info whatsoever.

**Comment by gkioxari** [comment]
Hi @zshyang. There hasn't been a response so I will be closing the task.
