### ISSUE TITLE
Evaluation hangs when num_workers > 0

### ISSUE THREAD

**Issue by natlouis** [facebookresearch/meshrcnn#25]
I can execute the following line to perform evaluation on the ShapeNet dataset, but only when num_workers=0.

```
python tools/train_net_shapenet.py --eval-only --num-gpus 1 \
--config-file configs/shapenet/voxmesh_R50.yaml \
MODEL.CHECKPOINT shapenet://voxmesh_R50.pth
```

Whenever I increase the number of workers to anything >0, the process hangs and never gets past the first mini batch. It seems to get stuck right before the postprocess function of the data loader, which is never executed: https://github.com/facebookresearch/meshrcnn/blob/master/shapenet/data/mesh_vox.py#L211.

Environment details:
sys.platform              linux
Python                    3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) [GCC 7.3.0]
numpy                     1.18.1
detectron2                0.1.1 @/home/user/miniconda3/envs/pytorch3d/lib/python3.6/site-packages/detectron2
detectron2 compiler       GCC 7.3
detectron2 CUDA compiler  10.0
detectron2 arch flags     sm_35, sm_37, sm_50, sm_52, sm_60, sm_61, sm_70, sm_75
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/user/miniconda3/envs/pytorch3d/lib/python3.6/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     GeForce GTX 1080 Ti
CUDA_HOME                 /z/sw/packages/cuda/10.0
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    6.0.0
torchvision               0.5.0 @/home/user/miniconda3/envs/pytorch3d/lib/python3.6/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0
------------------------  -----------

**Comment by gkioxari** [comment]
Hi @natlouis. The number of workers on the data loader does not affect the `postprocess` function, which is executed outside the data loader after the batch is fetched (see [here](https://github.com/facebookresearch/meshrcnn/blob/master/tools/train_net_shapenet.py#L155) for train, and [here](https://github.com/facebookresearch/meshrcnn/blob/master/shapenet/evaluation/eval.py#L53) for eval). I will try to reproduce your error in the following days, likely tomorrow or the day after and will post here again.

**Comment by gkioxari** [comment]
@natlouis I ran evaluation and it works fine for me with the default setting. Nothing hangs. If you could provide more info I'm happy to help.

**Comment by natlouis** [comment]
Okay, I re-installed everything from scratch again and it worked. The only difference is that I switched to Python 3.8 and before I was using Python 3.6. 
I'm not sure why that made a difference, but either way it was an issue on my end. Thanks for your help.

**Comment by gkioxari** [comment]
Great! I am glad things are working now! I will close this issue, but feel free to re-open it if anything comes up.
