### ISSUE TITLE
Issue: RuntimeError: Not compiled with GPU support.

### ISSUE THREAD

**Issue by tasuka98** [facebookresearch/meshrcnn#27]
Hi, I tried running the script after installing all the dependencies and received the following error. I have installed both pytorch3d as well as detectron2 correctly by following the instruction for cuda 10.1 but I don't know why I am still receiving this error.

`(base) tasuka@tasuka-TM1701:~/Desktop/meshrcnn$ python3 demo/demo.py --config-file configs/pix3d/meshrcnn_R50_FPN.yaml --input ./input/sofa.jpg --output output_demo --onlyhighest MODEL.WEIGHTS meshrcnn://meshrcnn_R50.pth`

`[05/04 01:44:37 demo]: Arguments: Namespace(config_file='configs/pix3d/meshrcnn_R50_FPN.yaml', focal_length=20.0, input='./input/sofa.jpg', onlyhighest=True, opts=['MODEL.WEIGHTS', 'meshrcnn://meshrcnn_R50.pth'], output='output_demo')
/pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:`
	`nonzero(Tensor input, *, Tensor out)`
`Consider using one of the following signatures instead:`
	`nonzero(Tensor input, *, bool as_tuple)`

`/pytorch/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.`

`Traceback (most recent call last):`
  `File "demo/demo.py", line 227, in <module>`
     `predictions = demo.run_on_image(img, focal_length=args.focal_length)`

  `File "demo/demo.py", line 59, in run_on_image`
    `predictions = self.predictor(image)`

 ` File "/home/tasuka/Desktop/detectron2/detectron2/engine/defaults.py", line 218, in __call__`
    `predictions = self.model([inputs])[0]`

 ` File "/home/tasuka/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__`
    `result = self.forward(*input, **kwargs)`

  `File "/home/tasuka/Desktop/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 108, in forward`
   ` return self.inference(batched_inputs)`

  `File "/home/tasuka/Desktop/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 170, in inference`
   ` results, _ = self.roi_heads(images, features, proposals, None)`

 ` File "/home/tasuka/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__`
   ` result = self.forward(*input, **kwargs)`

 ` File "/home/tasuka/Desktop/meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 164, in forward`
   ` pred_instances = self.forward_with_given_boxes(features, pred_instances)`

  `File "/home/tasuka/Desktop/meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 185, in forward_with_given_boxes`
   ` instances = self._forward_shape(features, instances)`

 ` File "/home/tasuka/Desktop/meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 357, in _forward_shape`
   ` pred_meshes = self.mesh_head(mesh_features, init_mesh)`

 ` File "/home/tasuka/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__`
    `result = self.forward(*input, **kwargs)`

  `File "/home/tasuka/Desktop/meshrcnn/meshrcnn/modeling/roi_heads/mesh_head.py", line 228, in forward`
   ` mesh, vert_feats = stage(x, mesh, vert_feats=vert_feats)`

 ` File "/home/tasuka/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__`
    `result = self.forward(*input, **kwargs)`

 ` File "/home/tasuka/Desktop/meshrcnn/meshrcnn/modeling/roi_heads/mesh_head.py", line 183, in forward`
    `vert_feats_nopos = F.relu(graph_conv(vert_feats, mesh.edges_packed()))`

 ` File "/home/tasuka/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__`
    `result = self.forward(*input, **kwargs)`

  `File "/home/tasuka/anaconda3/lib/python3.7/site-packages/pytorch3d/ops/graph_conv.py", line 71, in forward`
   ` neighbor_sums = gather_scatter(verts_w1, edges, self.directed)`

  `File "/home/tasuka/anaconda3/lib/python3.7/site-packages/pytorch3d/ops/graph_conv.py", line 154, in forward`
   ` output = _C.gather_scatter(input, edges, directed, backward)`

`RuntimeError: Not compiled with GPU support.`

**Comment by nitinsurya** [comment]
Have tried fixing the pytorch version to 1.4 and torchvision to 0.5.0? This command fixed it for me:
`conda install -c pytorch pytorch==1.4 torchvision==0.5.0`
I suspect this error is raised now due to new pytorch version 1.5.

**Comment by gkioxari** [comment]
It seems that you haven't been able to build PyTorch3D with cuda. I am not an expert in resolving installation issues but could you take a look at PyTorch3D's issues under the *installation* label? I will also try to get some more insight into how we can resolve your issue.

**Comment by bottler** [comment]
@tasuka98 Can you paste the output of `conda list` please? Did you install pytorch3d with conda - which is the easiest way?

**Comment by tasuka98** [comment]
> Tried fixing the pytorch version to 1.4 and torchvision to 0.5.0? This command fixed it for me:
> `conda install -c pytorch pytorch==1.4 torchvision==0.5.0`
> I suspect this error is raised now due to new pytorch version 1.5.

I have tried to install them but the command only install them for CPU, and If I were to install them for cuda I need to downgrade it to 10.0, so should I do that instead?

**Comment by tasuka98** [comment]
Thanks everyone for their help! 

@bottler I tried to reinstall pytorch3d along with torch and torchvision using conda and I was able to get the demo running by using the pre-built version of detectron2 for cuda10.1! Thank you.
