### ISSUE TITLE
Getting the Voxel outputs

### ISSUE THREAD

**Issue by ShashwatNigam99** [facebookresearch/meshrcnn#28]
I wish to tap into the network output in the middle. I want to retrieve the voxel representation before it is sent to the mesh refinement branch. Can anyone point me to as to where this is done/ how to do so?

**Comment by gkioxari** [comment]
For the Pix3D models:

During training
https://github.com/facebookresearch/meshrcnn/blob/32dfa7ff9e321b08a250f550ac65b9effd80dd1c/meshrcnn/modeling/roi_heads/roi_heads.py#L287-L288

During inference
https://github.com/facebookresearch/meshrcnn/blob/32dfa7ff9e321b08a250f550ac65b9effd80dd1c/meshrcnn/modeling/roi_heads/roi_heads.py#L344-L345

`vox_in` is the voxel with probabilities which is then being converted into a mesh via the cubify operation. 

For ShapeNet:
https://github.com/facebookresearch/meshrcnn/blob/32dfa7ff9e321b08a250f550ac65b9effd80dd1c/shapenet/modeling/mesh_arch.py#L82

**Comment by ShashwatNigam99** [comment]
Thank you so much for the prompt reply, I will try it out!

**Comment by ShashwatNigam99** [comment]
I am able to retrieve the **N*V*V*V** voxel grid. (Which I understand are the voxel representations(probabilities) of N identified objects).

 - What deteremines the size of V? Can I increase/decrease V for denser/sparser sampling?

- What threshold should I set for the voxel probabilities in order to visualize in voxel space?

- How can I get the orientation/location of the predicted voxels in camera space?

**Comment by gkioxari** [comment]
> What deteremines the size of V? Can I increase/decrease V for denser/sparser sampling?

Please refer to the voxel head in the model https://github.com/facebookresearch/meshrcnn/blob/32dfa7ff9e321b08a250f550ac65b9effd80dd1c/meshrcnn/modeling/roi_heads/voxel_head.py#L127

The voxel head pools features of size `MxM` where M is specified by `cfg.MODEL.ROI_VOXEL_HEAD.POOLER_RESOLUTION` and the CNN upsamples that to `2Mx2M`. For our models, we pick `M = 12` as seen in the configs
https://github.com/facebookresearch/meshrcnn/blob/32dfa7ff9e321b08a250f550ac65b9effd80dd1c/configs/pix3d/meshrcnn_R50_FPN.yaml#L33

> What threshold should I set for the voxel probabilities in order to visualize in voxel space?

This is up to you. Try 0.5? When we train Mesh R-CNN models, we pick something lower (e.g. 0.3) which leaves room for the subsequent mesh refinement head to correct for shape. 

> How can I get the orientation/location of the predicted voxels in camera space?

The voxel predictions are in camera space already. In other words, the voxel predictions of the object are in the position/orientation seen in the input image.

**Comment by ShashwatNigam99** [comment]
### Scene considered (taking the 2 sofas)
![0_mask_sofa_1 000](https://user-images.githubusercontent.com/30972206/81484512-8e988800-9263-11ea-8180-0a38bb3f82c7.png)
### Rendering the final meshes in blender, they come out in the correct orientation and position with respect to each other, as you said.
![2](https://user-images.githubusercontent.com/30972206/81484518-97895980-9263-11ea-915e-7ba43d46362d.png)
### Voxel Rendering:
#### Sofa 1
![Figure_1](https://user-images.githubusercontent.com/30972206/81484507-86d8e380-9263-11ea-8b27-7213a53090c4.png)
#### Sofa 2
![Figure_2](https://user-images.githubusercontent.com/30972206/81484508-893b3d80-9263-11ea-90a7-8ad58b149b48.png)
#### Combined in voxel space
![Figure_3](https://user-images.githubusercontent.com/30972206/81484510-8b9d9780-9263-11ea-8b54-bad543efdc2a.png)

I took the vox_in tensor ( N x V x V x V ) and took the top 2 and visualized in voxel space.
Here I have used threshold as 0.5.
They don't seem to be aligned properly here.
Can you tell me where I am going wrong?

Here is the short visualization code I wrote. 'vox_in.pt' is the tensor I retrieved from inference.
https://github.com/facebookresearch/meshrcnn/blob/32dfa7ff9e321b08a250f550ac65b9effd80dd1c/meshrcnn/modeling/roi_heads/roi_heads.py#L344-L345

```
import torch
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

VOXEL_TENSOR = "vox_in.pt"
THRESH = 0.5

tensorx = torch.load(VOXEL_TENSOR)
print(tensorx.shape)

fig = plt.figure()
ax = fig.gca(projection='3d')

ax.voxels((tensorx[0]>THRESH)*1,edgecolor="k")
ax.voxels((tensorx[1]>THRESH)*1,edgecolor="k")

plt.show()
```

**Comment by gkioxari** [comment]
Oh I think there is a confusion. So the voxels that are predicted with shape`NxVxVxV` (i.e. the outputs of the voxel heads) are confined in their predicted object bounding box, basically think of a 3D bounding box tight around the object instance in the image. Within that 3D object bounding box, the voxel predictions will correspond to the object's pose/shape in the camera coordinate system.

The 3D object shapes are placed back into the image, just as you show in the 2nd image from blender here. 

https://github.com/facebookresearch/meshrcnn/blob/32dfa7ff9e321b08a250f550ac65b9effd80dd1c/demo/demo.py#L95

So if you wish to visualize the voxels and not the final meshes, then take the voxel outputs, convert them to meshes through cubify and then use those cubified meshes as input to `transform_meshes_to_camera_coord_system`

**Comment by gkioxari** [comment]
I am closing this issue but feel free to re-open it if anything else comes up!
