### ISSUE TITLE
function of the ROI_Z_Head

### ISSUE THREAD

**Issue by pieterbl86** [facebookresearch/meshrcnn#30]
@gkioxari 
thanks for the great repository. 

when scrolling through the source code, I found the ROI head construction (meshrcnn/modelling/roi_heads). 

In there, there's a z_head branch. I cannot figure out what this head branch is doing. Is it there to detect the z-coordinates of the mask?

thanks in advance.

**Comment by gkioxari** [comment]
Hi @pieterbl86 
The `z_head` predicts the extent of an object bounding box in the Z axis. This in addition to the bounding box regressor head from Mask R-CNN, provides a tight 3D bounding box for each detected object. For more details about the `z_head` please refer to Appendix E in https://arxiv.org/pdf/1906.02739.pdf

**Comment by gkioxari** [comment]
Hi @pieterbl86 
I hope I answered your question. I will be closing this issue now. Feel free to re-open if you have more questions.

**Comment by pieterbl86** [comment]
> Hi @pieterbl86
> I hope I answered your question. I will be closing this issue now. Feel free to re-open if you have more questions.

yes, the question has been answered, thanks!
