### ISSUE TITLE
Invalid multinomial distribution for poor predictions

### ISSUE THREAD

**Issue by umyta** [facebookresearch/meshrcnn#32]
Hi, @gkioxari, 
I have a question regarding the `compare_meshes` function used in `pix3d_evaluation.py`. I tried this function on a new dataset and got some poor predictions during evaluation for various reasons. I understand if this is out of the scope of issues. I just want to see if you can give me some advice on how to avoid getting errors like this during evaluation. Any suggestions would be much appreciated!

During the evaluation, I first got the following error:
```
...
../pytorch3d/ops/sample_points_from_meshes.py line 71
sample_face_idxs += mesh_to_face[meshes.valid].view(num_valid_meshes, 1)
RuntimeError: copy_if failed to synchronize: device-side assert triggered"
```
Then, I saved all meshes and called compare_meshes in a notebook. I found that for some meshes, such as this [pred](https://drive.google.com/open?id=1_4dbeBWEB63zSXi7ByXU8HUPMUnUho12) and [gt](https://drive.google.com/open?id=1A65PvNpRmtqW2uLzBZSkEhEWKcjRkAVE) pair,  I got "invalid multinomial distribution (sum of probabilities <= 0)" error, which might be causing the error above. The full bt looks like this:
```
----> 9         shape_metrics = compare_meshes(pred_meshes, gt_meshes, reduce=False)

.../python3.6/site-packages/torch/autograd/grad_mode.py in decorate_no_grad(*args, **kwargs)
     47         def decorate_no_grad(*args, **kwargs):
     48             with self:
---> 49                 return func(*args, **kwargs)
     50         return decorate_no_grad
     51 

.../meshrcnn/meshrcnn/utils/metrics.py in compare_meshes(pred_meshes, gt_meshes, num_samples, scale, thresholds, reduce, eps)
     65         num_samples_pred = num_samples_gt = num_samples
     66 
---> 67     pred_points, pred_normals = _sample_meshes(pred_meshes, num_samples_pred)
     68     gt_points, gt_normals = _sample_meshes(gt_meshes, num_samples_gt)
     69     if pred_points is None:

.../meshrcnn/meshrcnn/utils/metrics.py in _sample_meshes(meshes, num_samples)
    154             verts = meshes.verts_list
    155     else:
--> 156         verts, normals = sample_points_from_meshes(meshes, num_samples, return_normals=True)
    157     return verts, normals
    158 

.../pytorch3d/pytorch3d/ops/sample_points_from_meshes.py in sample_points_from_meshes(meshes, num_samples, return_normals)
     63         sample_face_idxs = areas_padded.multinomial(
     64             num_samples, replacement=True
---> 65         )  # (N, num_samples)
     66 
     67         # print("meshes.valid", meshes.valid)

RuntimeError: invalid multinomial distribution (sum of probabilities <= 0)
```

Here is a snapshot of the first couple of vertices in the predicted obj file. As you can see there are a lot of repeated vertices.
```
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834222
v -1.661227 1.381543 3.834222
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834222
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834222
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834222
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834222
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834222
v -1.661227 1.381543 3.834221
v -1.661227 1.381543 3.834221
```
I was wondering if you would have any suggestions on how to avoid errors like this. My apologies if I post it on the wrong place. Thanks in advance!

**Comment by gkioxari** [comment]
@umyta I will try to help you on this after the NeurIPS submission.

**Comment by gkioxari** [comment]
Hi @umyta 
Sorry for the late response. Did you figure this out? 
The error that you are getting wrt the multinomial seems to suggest that the meshes are not regular. Have you tried to visualize them? I have never run into an issue like this before.

**Comment by umyta** [comment]
@gkioxari , I have not yet figured this out. Yes, the predicted mesh is really bad which triggered this during evaluation. My current strategy is to see if I can by-pass this function during evaluation. Any suggestions would be appreciated.

**Comment by gkioxari** [comment]
The error occurs when trying to sample points. The function that samples points computes the areas of the mesh faces (predicted or ground truth) and samples points proportional to that area. For example if a face `f` has area `area(f)` then it will sample `N * area(f)/sum(area(f))`. Your error seems to suggest that the areas of the faces are 0. Could you verify this? This seems bizarre and not just a matter of poor quality predictions. Somehow your model predicts 0-faced areas for all faces in the  mesh.

**Comment by umyta** [comment]
I think you are right. If the prediction is just repeated points, the areas of the faces should be 0. Thank you for the help!

**Comment by umyta** [comment]
Just want to add an update. I don't know if it's a fix, but what I found is that [num_valid_meshes](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/ops/sample_points_from_meshes.py#L49) could be [] if none of the predicted meshes are good. In this case, it will trigger the error [here](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/ops/sample_points_from_meshes.py#L66). The workaround I'm using right now is to check `if len(num_valid_meshes.shape) == 0`, if so, avoid sampling.

**Comment by AnanthK1998** [comment]
Hi @umyta , may I know how you solved this?
