### ISSUE TITLE
How to download the `ShapeNet` dataset?

### ISSUE THREAD

**Issue by zshyang** [facebookresearch/meshrcnn#34]
Hi,
As mentioned in your instruction,
```
You also need the original ShapeNet Core v1 & binvox dataset, which require registration before downloading.
```
I am not sure where to download the `binvox` dataset. Could you have me with it?

**Comment by gkioxari** [comment]
You have asked this before and folks have responded to your question https://github.com/facebookresearch/meshrcnn/issues/21

**Comment by zshyang** [comment]
Thanks! My bad.
