### ISSUE TITLE
meshrcnn_R50.pth Should be placed in that folder

### ISSUE THREAD

**Issue by zyz-1998** [facebookresearch/meshrcnn#35]
meshrcnn_R50.pth Should be placed in that folder, I failed to download it when I run proxychains python demo/demo.py --config-file configs/pix3d/meshrcnn_R50_FPN.yaml --input /path/to/image --output output_demo --onlyhighest MODEL.WEIGHTS meshrcnn://meshrcnn_R50.pth often, it is not clear where to place it after downloading separately, thank you very much

**Comment by gkioxari** [comment]
Pathmanager should download this for you and place it in a tmp directory. You should be able to run the command without having to explicitly download the model. (Detectron2 does the same)

https://github.com/facebookresearch/meshrcnn/blob/ab0762f87bfd4cbdf4560982c5c33832a445380b/meshrcnn/utils/model_zoo.py#L8

If you don't like this functionality then feel free to manually download the model and place it somewhere in your machine and change `MODEL.WEIGHTS /my/path/to/weights/`.

**Comment by gkioxari** [comment]
Closing this as it's a non issue.

**Comment by Mr-MVP** [comment]
> Pathmanager should download this for you and place it in a tmp directory. You should be able to run the command without having to explicitly download the model. (Detectron2 does the same)
> 
> https://github.com/facebookresearch/meshrcnn/blob/ab0762f87bfd4cbdf4560982c5c33832a445380b/meshrcnn/utils/model_zoo.py#L8
> 
> If you don't like this functionality then feel free to manually download the model and place it somewhere in your machine and change `MODEL.WEIGHTS /my/path/to/weights/`.

Can you please provide a site or a link from where we can download this weight ?
