### ISSUE TITLE
Any idea about how to fix the following bug?

### ISSUE THREAD

**Issue by zshyang** [facebookresearch/meshrcnn#36]
It seems that the box loss became NaN at some point.

```
FloatingPointError: Loss became infinite or NaN at iteration=756!
loss_dict = {'loss_cls': tensor(nan, device='cuda:1', grad_fn=<NllLossBackward>), 
'loss_box_reg': tensor(nan, device='cuda:1', grad_fn=<DivBackward0>), 'loss_z_reg': 
tensor(nan, device='cuda:1', grad_fn=<DivBackward0>), 'loss_mask': tensor(nan, 
device='cuda:1', grad_fn=<BinaryCrossEntropyWithLogitsBackward>), 'loss_voxel': tensor(nan, 
device='cuda:1', grad_fn=<MulBackward0>), 'loss_chamfer': tensor(-0., device='cuda:1', 
grad_fn=<MulBackward0>), 'loss_normals': tensor(-0., device='cuda:1', grad_fn=
<MulBackward0>), 'loss_edge': tensor(-0., device='cuda:1', grad_fn=<MulBackward0>), 
'loss_rpn_cls': tensor(nan, device='cuda:1', grad_fn=<MulBackward0>), 'loss_rpn_loc': 
tensor(inf, device='cuda:1', grad_fn=<MulBackward0>)}
```

**Comment by gkioxari** [comment]
Your optimization is diverging. Start with decreasing the learning rate.

**Comment by zshyang** [comment]
Thanks a lot!

**Comment by purugupta99** [comment]
`FloatingPointError: Loss became infinite or NaN at iteration=8!
loss_dict = {'loss_cls': tensor(0.9525, device='cuda:1', grad_fn=<NllLossBackward>), 'loss_box_reg': tensor(0., device='cuda:1', grad_fn=<DivBackward0>), 'loss_z_reg': tensor(nan, device='cuda:1', grad_fn=<DivBackward0>), 'loss_mask': tensor(5.8197, device='cuda:1', grad_fn=<BinaryCrossEntropyWithLogitsBackward>), 'loss_voxel': tensor(2.0721, device='cuda:1', grad_fn=<MulBackward0>), 'loss_chamfer': tensor(0., device='cuda:1', grad_fn=<MulBackward0>), 'loss_normals': tensor(0., device='cuda:1', grad_fn=<MulBackward0>), 'loss_edge': tensor(0., device='cuda:1', grad_fn=<MulBackward0>), 'loss_rpn_cls': tensor(0.3055, device='cuda:1', grad_fn=<MulBackward0>), 'loss_rpn_loc': tensor(0.0218, device='cuda:1', grad_fn=<MulBackward0>)}
` <br>
We tried reducing the BASE_LR in config.yaml but still face similar error. Can you suggest something we can try?
