### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 442.00 MiB (GPU 0; 15.90 GiB total capacity; 14.37 GiB already allocated; 193.88 MiB free; 14.92 GiB reserved in total by PyTorch) while trying to train using trainer.train()

### ISSUE THREAD

**Issue by shatadru99** [facebookresearch/meshrcnn#37]
I am trying to train meshrcnn on the Pix3D dataset in Google Colab using GPU backend and 25GB RAM space. I am trying to implement it myself without explicitly calling the /tools/train_net.py file.

So, I first created a Namespace type object having the required arguments:
`args = Namespace(config_file='configs/pix3d/meshrcnn_R50_FPN.yaml', dist_url='tcp://127.0.0.1:49152', eval_only=False, machine_rank=0, num_gpus=8, num_machines=1, opts=[], resume=False)`
**Now, I changed the MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE to 8 in place of 64 in 'configs/pix3d/meshrcnn_R50_FPN.yaml' file and used it so that Colab does not run out of memory)**

I then created a cfg variable and included all the necessary keys and default values:
`cfg = get_cfg()`
`get_meshrcnn_cfg_defaults(cfg)    ##get_meshrcnn_cfg_defaults imported from meshrcnn`
`cfg.merge_from_file(args.config_file)`
`cfg.merge_from_list(args.opts)`
`cfg.freeze()`
`default_setup(cfg, args)  ##default_setup imported from detectron2`

Then I created the trainer object and tried to train:
`trainer = Trainer(cfg)`
`trainer.resume_or_load(resume=args.resume)`
`trainer.train()`

But I am getting "RuntimeError: CUDA out of memory. Tried to allocate 442.00 MiB (GPU 0; 15.90 GiB total capacity; 14.37 GiB already allocated; 193.88 MiB free; 14.92 GiB reserved in total by PyTorch)"
I double checked that GPU was NOT utilised 100% from the bar above which shows the utlised RAM. Only 5.27GB/25GB was utilised.

**Ways to reproduce my code:**
[This is my Google Colab Notebook link](https://colab.research.google.com/drive/1z86NKDAit98ZJHoCFzNQXDe71B8SqK1z?usp=sharing)

**Is there any way (like, changing some other parameter values or something) by which I can train the meshrcnn model on Pix3D dataset in Google Colab?**

@gkioxari kindly look into it.
pytorch3d version is '0.2.0'
torchvision version is '0.6.0+cu101'

I also checked for similar type of issues in pytorch forums but could not solve this problem.

The Error:
[06/06 04:39:45 d2.engine.train_loop]: Starting training from iteration 0
ERROR [06/06 04:39:46 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py", line 121, in forward
    features = self.backbone(images.tensor)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/backbone/fpn.py", line 136, in forward
    results.insert(0, output_conv(prev_features))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/layers/wrappers.py", line 93, in forward
    x = super().forward(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 442.00 MiB (GPU 0; 15.90 GiB total capacity; 14.37 GiB already allocated; 193.88 MiB free; 14.92 GiB reserved in total by PyTorch)
[06/06 04:39:46 d2.engine.hooks]: Total training time: 0:00:01 (0:00:00 on hooks)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-20-c502e6cbf4d7> in <module>()
      1 #This is where we are having errors
----> 2 trainer.train()

10 frames
/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py in train(self)
    399             OrderedDict of results, if evaluation is enabled. Otherwise None.
    400         """
--> 401         super().train(self.start_iter, self.max_iter)
    402         if len(self.cfg.TEST.EXPECTED_RESULTS) and comm.is_main_process():
    403             assert hasattr(

/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    130                 for self.iter in range(start_iter, max_iter):
    131                     self.before_step()
--> 132                     self.run_step()
    133                     self.after_step()
    134             except Exception:

/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py in run_step(self)
    213         If you want to do something with the losses, you can wrap the model.
    214         """
--> 215         loss_dict = self.model(data)
    216         losses = sum(loss_dict.values())
    217         self._detect_anomaly(losses, loss_dict)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py in forward(self, batched_inputs)
    119             gt_instances = None
    120 
--> 121         features = self.backbone(images.tensor)
    122 
    123         if self.proposal_generator:

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/backbone/fpn.py in forward(self, x)
    134             if self._fuse_type == "avg":
    135                 prev_features /= 2
--> 136             results.insert(0, output_conv(prev_features))
    137 
    138         if self.top_block is not None:

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/detectron2/layers/wrappers.py in forward(self, x)
     91                 return empty
     92 
---> 93         x = super().forward(x)
     94         if self.norm is not None:
     95             x = self.norm(x)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py in forward(self, input)
    347 
    348     def forward(self, input):
--> 349         return self._conv_forward(input, self.weight)
    350 
    351 class Conv3d(_ConvNd):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py in _conv_forward(self, input, weight)
    344                             _pair(0), self.dilation, self.groups)
    345         return F.conv2d(input, weight, self.bias, self.stride,
--> 346                         self.padding, self.dilation, self.groups)
    347 
    348     def forward(self, input):

RuntimeError: CUDA out of memory. Tried to allocate 442.00 MiB (GPU 0; 15.90 GiB total capacity; 14.37 GiB already allocated; 193.88 MiB free; 14.92 GiB reserved in total by PyTorch)

**Besides that. I also tried using:**
`python tools/train_net.py --num-gpus 1 \`
`--config-file configs/pix3d/meshrcnn_R50_FPN.yaml`
That also gave same type of error:
RuntimeError: CUDA out of memory

**Comment by gkioxari** [comment]
I have never tried training this Colab. However, when training on V100 the GPU memory occupied is maximum 7GB per GPU (which is half the V100 capacity).

Some random thoughts in an effort to figure this out. 
* I though that Google Colab only provides M40s and only one GPU and not a machine of 8 GPUs. However, in your specifications you request a full machine of 8 GPUs. 
* Is it possible that the Colab GPU is already running something else (e.g. shared)? This could explain this. Is there a way to check what the GPU type is and whether it's shared.
* Note that by default the batch size for training is 16 images (8 GPUs * 2 images / GPU). When training with `--num-gpus 1` you need to change this to `2`. Of course training with one GPU is going to give you bad results. 
* In an effort to further understand the Colab memory usage, it's worth trying to set the batch size to 1 image per GPU and trying this out.

https://github.com/facebookresearch/meshrcnn/blob/ab0762f87bfd4cbdf4560982c5c33832a445380b/configs/pix3d/MESH-RCNN-FPN.yaml#L51

**Comment by gkioxari** [comment]
No response. Closing this. Feel free to re-open.
