### ISSUE TITLE
Demo in ShapeNet

### ISSUE THREAD

**Issue by RohDonghyeon** [facebookresearch/meshrcnn#41]
Thank you for providing good code.
I want to check 3D reconstruction Object in ShapeNet like Demo.
How can i ?

**Comment by gkioxari** [comment]
We don't provide a demo for ShapeNet. If you want to evaluate on ShapeNet test (according to the R2N2 splits), please follow the instructions: https://github.com/facebookresearch/meshrcnn/blob/master/INSTRUCTIONS_SHAPENET.md#testing-and-evaluation.

**Comment by RohDonghyeon** [comment]
The demo.py provided a 3D obj file as a result when a custom image was inserted.

I checked the test and evaluation code, and I also checked the score.

But I want to perform 3D reconstruction with a custom image.

Is there any way?

**Comment by h3xh4wk** [comment]
Hi @RohDonghyeon, were you able to try 3D reconstruction with `shapenet` configs? Is it possible? What changes need to be done. I checked demo.py. Looks like it can be adapted for shapenet too. Maybe @gkioxari can give some pointers.

**Comment by gkioxari** [comment]
Hey @h3xh4wk and @RohDonghyeon 
I will not be providing a demo for shapenet. It is easy to write your own demo though. Follow the evaluation code (follow the `args.eval_only` flag in `train_net_shapenet`) for ShapeNet and you will be able to do this quickly for your own images.

**Comment by gkioxari** [comment]
I am closing this!

**Comment by Ulia-Demidova** [comment]
Hi @gkioxari !
I want to write a demo for shapenet.
Model for shapenet doesn't provide 2d masks and boxes for image, does it? Does the model provide only meshes?

**Comment by p4p3rb0y1** [comment]
Thanks @gkioxari . I am checking `train_net_shapenet`. On initial tries, training with even batch_size of 4 is making the GPU ( I have only 1 GPU with 4gb mem ) run out of memory at about 650th iteration. I did not change any other parameter in `voxmesh` model. Do I need to upgrade the GPU or add more ? or is it possible for modify the parameters that are suitable for training with this meager resources for now.

Also is it possible that I could train on just a few synsets, particularly the ones that are relevant with respect to custom images? Will that approach help in overcoming the challenge with memory and storage?

**Comment by h3xh4wk** [comment]
Thanks @gkioxari . I am checking train_net_shapenet. On initial tries, training with even batch_size of 4 is making the GPU ( I have only 1 GPU with 4gb mem ) run out of memory at about 650th iteration. I did not change any other parameter in voxmesh model. Do I need to upgrade the GPU or add more ? or is it possible for modify the parameters that are suitable for training with this meager resources for now.

Also is it possible that I could train on just a few synsets, particularly the ones that are relevant with respect to custom images? Will that approach help in overcoming the challenge with memory and storage?

**Comment by engrmz** [comment]
H

> Thanks @gkioxari . I am checking train_net_shapenet. On initial tries, training with even batch_size of 4 is making the GPU ( I have only 1 GPU with 4gb mem ) run out of memory at about 650th iteration. I did not change any other parameter in voxmesh model. Do I need to upgrade the GPU or add more ? or is it possible for modify the parameters that are suitable for training with this meager resources for now.
> 
> Also is it possible that I could train on just a few synsets, particularly the ones that are relevant with respect to custom images? Will that approach help in overcoming the challenge with memory and storage?

Hi @h3xh4wk and @RohDonghyeon, 
If you are successful in creating demo file for ShapeNet images, please share with me too. Thank you.

**Comment by grEmsIsY** [comment]
@engrmz Do you have demo for ShapNet yet?
