### ISSUE TITLE
Issue with installation: RuntimeError: Not compiled with GPU support

### ISSUE THREAD

**Issue by Sayan-m90** [facebookresearch/meshrcnn#43]
**Hello I tried running the demo file after installation of meshrcnn. This is the error I get:**

` python demo/demo.py --config-file configs/pix3d/meshrcnn_R50_FPN.yaml --input chic-open-floor-plan.png --o
utput output_demo --onlyhighest MODEL.WEIGHTS meshrcnn://meshrcnn_R50.pth
[06/24 23:35:08 demo]: Arguments: Namespace(config_file='configs/pix3d/meshrcnn_R50_FPN.yaml', focal_length=20.0, input='chic-open-floor-plan.png
', onlyhighest=True, opts=['MODEL.WEIGHTS', 'meshrcnn://meshrcnn_R50.pth'], output='output_demo')
/opt/conda/conda-bld/pytorch_1591914858187/work/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:
        nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
        nonzero(Tensor input, *, bool as_tuple)
/opt/conda/conda-bld/pytorch_1591914858187/work/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is
 deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
Traceback (most recent call last):
  File "demo/demo.py", line 227, in <module>
    predictions = demo.run_on_image(img, focal_length=args.focal_length)
  File "demo/demo.py", line 59, in run_on_image
    predictions = self.predictor(image)
`
**I am working on cuda 10.2. I have installed pytorch3d using conda and the prebuilt library of detectron2 for cuda 10.2 and 1.5. I have looked at the previous issue #27 on related issue but i think I am installing everything correctly. Any help will be really appreciated
The conda list is in the image attached:** 
![Screenshot (21)](https://user-images.githubusercontent.com/16404344/85638281-82219080-b653-11ea-8879-a01ba84ea9d7.png)
![Screenshot (22)](https://user-images.githubusercontent.com/16404344/85638282-82ba2700-b653-11ea-8af9-b9963f7a9b05.png)
![Screenshot (23)](https://user-images.githubusercontent.com/16404344/85638283-82ba2700-b653-11ea-989f-ed1d279fb1e0.png)
![Screenshot (24)](https://user-images.githubusercontent.com/16404344/85638284-8352bd80-b653-11ea-8af3-9e7d01af9afb.png)

**Comment by gkioxari** [comment]
Have you checked any of the other installation issues on this repo? I think there is some bizarreness with conda going on recently. @bottler might know more. 
In the meantime, have you tried installing from source?

**Comment by Sayan-m90** [comment]
There do not seem to be any other installation issues on this repos regarding this exact problem. Maybe I missed something? I have looked into similar issues in detectron2 and mask_rcnn but none seems to help.
wrt manual install, I did *python script.py build* follow by *script.py install*
but that doesn't do the trick either. is there any other way?

**Comment by gkioxari** [comment]
Have you successfully installed detectron2 and pytorch3d?

**Comment by bottler** [comment]
Pytorch3d has been installed from a wheel on pypi (rather than from source or from a conda package). The pytorch3d wheel on pypi is a CPU-only version.

**Comment by Sayan-m90** [comment]
that is weird. I had pytorch3d installed separately using:
`conda create -n pytorch3d python=3.8
conda activate pytorch3d
conda install -c pytorch pytorch torchvision cudatoolkit=10.2
conda install -c conda-forge -c fvcore fvcore`
given in the docs. maybe something else messed it up
also when i do "torch.cuda.is_available()" it returns True

**Comment by bottler** [comment]
Those are the commands to install dependencies of pytorch3d, e.g. pytorch, which is working with cuda. But none of those commands install pytorch3d. You probably intended `conda install pytorch3d -c pytorch3d` but omitted it. Something else must then have been forced to install pytorch3d automatically, and did it from pypi.

**Comment by gkioxari** [comment]
No response in 17 days. Closing this. Reopen if any issues arise.
