### ISSUE TITLE
mapping output to input

### ISSUE THREAD

**Issue by xiang-zhu127** [facebookresearch/meshrcnn#44]
Not sure if this is a issue. But is it possible to map the output mesh triangles to the image pixels? On reading the paper it says there exist a natural mapping. But can we get this from the model somehow?
Thanks is much help

**Comment by gkioxari** [comment]
I have written a note here that I think will be useful: https://github.com/facebookresearch/meshrcnn/tree/master/demo/README.md

**Comment by xiang-zhu127** [comment]
yes I did go through the write up and it is very helpful. but me being not good in blender, did you do the mapping on the image manually after you render using f=20? so I am trying to find a direct map between triangles and pixels automatically (preferably without a renderer), is there anyway to do that? thank you

**Comment by gkioxari** [comment]
I am not sure what you want to do. For the joint detection + shape setting (like Pix3D), each 2D box detection predicts a 3D mesh. The 3D mesh as being predicted by the mesh head is aligned to the 2D box (which we assume spans from -1 to 1 in both height and width). So the 3D shapes and 2D object regions are aligned by default. The codebase then transforms the predicted 3D shape spanning in [-1, 1] and aligns in in pixel-space with the image (modulo a scale which is proportional to f). The renderer just projects this on the image plane with the camera (here a perspective camera with f=20).

**Comment by gkioxari** [comment]
No response. I am closing this issue. Re-open it if anything new comes up.
