### ISSUE TITLE
Preprocessing ShapeNet

### ISSUE THREAD

**Issue by Ulia-Demidova** [facebookresearch/meshrcnn#47]
I downloaded ShapeNetCore.v1.zip and ShapeNetCore.v1.binvox.zip. Then I unzipped them and run preprocess_shapenet.py. Output:
Traceback (most recent call last):
  File "preprocess_shapenet.py", line 317, in <module>
    main(args)
  File "preprocess_shapenet.py", line 144, in main
    raise ValueError("Pre processing identified missing data points")
ValueError: Pre processing identified missing data points

Can you help me?

**Comment by h3xh4wk** [comment]
I faced the same error and realised that the download was incomplete. 
Also I hope you didn't miss r2n2 renderings.

**Comment by gkioxari** [comment]
It means your pre-processing did not complete correctly. There might be multiple issues for that. A safe way to fix it is to re-start the pre-processing from scratch or find the data points that are missing from the output and run the code only for those.

**Comment by gkioxari** [comment]
No response. Closing this.
