### ISSUE TITLE
Orthographic camera, t_z, focal_length

### ISSUE THREAD

**Issue by dmitrykudinov** [facebookresearch/meshrcnn#52]
Hi @gkioxari, 

1. In #22 you are talking about `t_z` true depth center per detected bbox, but i could not find this variable in the code - could you point us at it?

2. Not critical, but WRT Pix3D demo script - works great, although the reconstructions with larger `focal_length` values appear to come less distorted from my tests, e.g.:
`focal_length = 20.` : 
![image](https://user-images.githubusercontent.com/3879467/88117494-2c67d780-cb70-11ea-810c-c4736c78e2ab.png)

`focal_lnegth = 1000.`: ![image](https://user-images.githubusercontent.com/3879467/88117434-fcb8cf80-cb6f-11ea-9c85-47fd2c4d1eac.png)

3. I'm looking for ways to apply Mesh R-CNN to work with orthographic camera. What would be your recommendations here regarding the corresponding code changes, and the K matrix (would you go just with a very large `focal_length`, or recommend replacing it with true ortho projection matrix?), etc.

thank you

**Comment by gkioxari** [comment]
Re (1): When placing the object mesh in the 3D scene we assume it's centered around `t_z`. Note that `t_z` is inconsequential for the method and is only relevant for rendering the object back to the image for visualization. The important information that might be useful is that given the true depth center of the object (i.e. 2m from the image plane) and the focal length of the camera, Mesh R-CNN will return the object in its original scale. In other words, knowing these two scalar parameters (t_z and f), one can infer the true size of the object in the world. The `t_z` parameter is used in the demo code here:
https://github.com/facebookresearch/meshrcnn/blob/ab0762f87bfd4cbdf4560982c5c33832a445380b/demo/demo.py#L80

Re (2): I haven't played with the focal_length value too much. However, the prediction shouldn't change when using different focal lengths. The choice of focal_length only scales the prediction but doesn't change the shape of the prediction. This scaling happens here

https://github.com/facebookresearch/meshrcnn/blob/ab0762f87bfd4cbdf4560982c5c33832a445380b/demo/demo.py#L95

Re (3): We assume perspective camera throughout the codebase for both ShapeNet and Pix3D as the ground truth is indeed provided using perspective cameras. There is a few changes that need to happen in the roi-based preparation stage in detectron2 and in the final inference transforms -see link in (2).

**Comment by dmitrykudinov** [comment]
ReRe(2): >... The choice of focal_length only scales the prediction but doesn't change the shape of the prediction....

Indeed, the topology of the mesh isn't affected, I think it's the scaling along the Z-axis which gets affected by the `focal_length` somewhere in `transform_meshes_to_camera_coord_system` call-stack.

thank you for the input, closing this one for now.
