### ISSUE TITLE
Difficulty running demo.py on mac 

### ISSUE THREAD

**Issue by NikhilKanamarla** [facebookresearch/meshrcnn#53]
Hi, I followed the setup process for meshrcnn and detctron2

I am trying to run the demo script with this command on MacOS

python demo.py \
--config-file /Users/nk/Downloads/Michigan/Computer-Science/Code/meshrcnn/configs/pix3d/meshrcnn_R50_FPN.yaml \
--input /Users/nk/Downloads/sampleimage.HEIC \
--output /Users/nk/Downloads \
--onlyhighest MODEL.WEIGHTS meshrcnn://meshrcnn_R50.pth \

my Torch device in the demo script is set to CPU

<img width="1680" alt="Screen Shot 2020-08-01 at 11 57 53 PM" src="https://user-images.githubusercontent.com/12837489/89115242-1d2c3800-d454-11ea-8e19-91527e84f1db.png">

Do you have any advice?

**Comment by gkioxari** [comment]
You say 
> I am trying to run the demo script with this command on MacOS

Your laptop does not have a GPU support so it's trying to run on CPU. Mesh R-CNN requires GPU unfortunately.

**Comment by NikhilKanamarla** [comment]
> You say
> 
> > I am trying to run the demo script with this command on MacOS
> 
> Your laptop does not have a GPU support so it's trying to run on CPU. Mesh R-CNN requires GPU unfortunately.

Thanks for the info, and I appreciate your work. I will try running it on Google Colab, do you have a notebook for the demo script? Say hi to Justin Johnson!

**Comment by gkioxari** [comment]
I have no Colab notebook sorry.

**Comment by NikhilKanamarla** [comment]
Well, thank you for your help. I am a University of Michigan Computer Science Student interested in working at Justin Johnson's research group. We talked back in May, and he asked me to reach out to him in August for research opportunities. Do you know how I could get in touch with him? 

> I have no Colab notebook sorry.

**Comment by gkioxari** [comment]
Emailing is the best bet. I can't provide any more guidance here. Also this is no longer related to the codebase. Closing this for now!
