### ISSUE TITLE
Tranformation applied on the voxels.

### ISSUE THREAD

**Issue by AnuragSahu** [facebookresearch/meshrcnn#54]
I was wondering if there is any transformation applied to the meshes before voxelizing them, because I tried to regenerate the .mat files from the .obj files provided in the pix3d Dataset, This is related to

model : "model/bed/IKEA_BEDDINGE/model.obj"
and its corresponding 
voxel : "model/bed/IKEA_BEDDINGE/voxel.obj"

Here are the voxels visualized,

<img src = "https://raw.githubusercontent.com/AnuragSahu/Things-I-needed-to-be-Online/master/Error%20images/voxel_diffs.png">

The Images on the left are the voxels from the dataset provided in the dataset and the Images on right are the ones I have created from binvox, the provided mesh model(.obj) already is transformed in the translation [0, 0, 0] and rotation [pie/2, 0, 0](XYZ Euler), I had to rotate the model to [pie, 0, 0] to get the correct orientation shown in above Image.

But I can see that there is some translation present in the voxels. So are any transformations applied to the voxels?

**Comment by gkioxari** [comment]
Yes there is actually many transformations happening, at the image level and at the roi level. 
The .mat files in Pix3D provide voxels in canonical coordinates. These are transformed with rotation and translation to become aligned to the view of the particular image. The second transform happens per roi to align the voxels with the particular region of interest chosen by our region proposal network. 
The code for all this is here:

https://github.com/facebookresearch/meshrcnn/blob/ab0762f87bfd4cbdf4560982c5c33832a445380b/meshrcnn/data/meshrcnn_transforms.py#L70

https://github.com/facebookresearch/meshrcnn/blob/ab0762f87bfd4cbdf4560982c5c33832a445380b/meshrcnn/modeling/roi_heads/voxel_head.py#L54

**Comment by AnuragSahu** [comment]
I think that you misunderstood my question, I am concerned that the provided mesh and voxels are not having the same transformations before going the steps you mentioned.

**Comment by gkioxari** [comment]
The voxel and mesh are not aligned as is. You need to do some transforms as shown below. Everything is in the codebase which aligns meshes and voxels. If you follow that you will find your answers. 

https://github.com/facebookresearch/meshrcnn/blob/ab0762f87bfd4cbdf4560982c5c33832a445380b/meshrcnn/data/meshrcnn_transforms.py#L250

**Comment by AnuragSahu** [comment]
I think that the voxels are centrally aligned in the 128 X 128 X 128 space, I misunderstood that for some kind of transformation being applied to the voxels.

**Comment by gkioxari** [comment]
I think so! I don't remember concretely though. I remember having to figure all this out to align them for Mesh R-CNN.

**Comment by gkioxari** [comment]
Closing this! Reopen if you have more questions.

**Comment by trevor-taeyeop** [comment]
@AnuragSahu , Have you solved your problem just move to center?? (binvox -> center align)
