### ISSUE TITLE
Question about datasets of pix3D

### ISSUE THREAD

**Issue by YawningLiu** [facebookresearch/meshrcnn#55]
I run the command line in "INSTRUCTIONS_PIX3D.md" to train the model.

There was something wrong during the training process:
"SyntaxError: not a TIFF file (header b'' not valid)."

I checked up the datasets and found  that "exif" message of some images caused this error. I deleted  these images‘  "exif" message. Then training process worked.

However, I was wondering why I met this question, and deleting information of  some data is a right method or not. 
Is there something wrong in pix3d's datasets? Or it is just because my environment is Incorrect?

**Comment by YawningLiu** [comment]
The erro with original data:

**Comment by YawningLiu** [comment]
The error with original data about pix3d happened in :
  File "<...>/detectron2/detectron2/data/detection_utils.py", line 140, in _apply_exif_orientation
    exif = image.getexif()
  File "<...>/PIL/Image.py", line 1312, in getexif
    self._exif.load(exif_info)
  File "<...>/PIL/Image.py", line 3316, in load
    self._info = TiffImagePlugin.ImageFileDirectory_v2(self.head)
  File "<...>/PIL/TiffImagePlugin.py", line 467, in __init__
    raise SyntaxError("not a TIFF file (header %r not valid)" % ifh)
  File "<string>", line None
SyntaxError: not a TIFF file (header b'' not valid)

I deleted 'exif' message of images:
bookcase/0039.jpg;
sofa/1157.jpg
sofa/1826.jpg;
sofa/1825.jpg.

**Comment by gkioxari** [comment]
I don't know. I have never run into this issue before. You might want to check with the Pix3D folks.

**Comment by YawningLiu** [comment]
Thank you! I will check with the Pix3D folks.
