### ISSUE TITLE
how can I replace "Depth Extent Prediction" with input value 

### ISSUE THREAD

**Issue by ahmedshingaly** [facebookresearch/meshrcnn#56]
I wonder how can I use top view, side view, and front view to configure image to 3D modeling. 
the idea is: 
user inputs perspective view 2d image
model contains top, side, front view that guide meshrcnn to convert perspective view image to 3d model (more accurate) ? 
I am trying to get more accurate 3d model from image by feeding guiding information like depth of each vertex, normal direction, mesh edge connection. 

thank you in advance

**Comment by gkioxari** [comment]
Hi @ahmedshingaly 
I am not quite sure what you mean and what you want to do. It is easy to replace certain aspects of the model predictions with ground truth information. The code should be quite easy to follow.

**Comment by gkioxari** [comment]
I am closing this issue! Feel free to reopen if you have further questions.
