### ISSUE TITLE
Question: Intrinsic matrix in shapenet 

### ISSUE THREAD

**Issue by dmitrykudinov** [facebookresearch/meshrcnn#57]
I am somewhat puzzled by the dimensionality of the blender intrinsic matrix returned by [get_blender_intrinsic_matrix](https://github.com/facebookresearch/meshrcnn/blob/1c8cbad1bc9a196f2e4fc0a80be6c12c35f1d1e3/shapenet/utils/coords.py#L30) - 4x4 instead of classical 4x3
![image](https://user-images.githubusercontent.com/3879467/93557089-03c14b80-f92f-11ea-8371-cdf0ead9ed2d.png)
...

Which consequently [results in a 4x4 Camera matrix P](https://github.com/facebookresearch/meshrcnn/blob/1c8cbad1bc9a196f2e4fc0a80be6c12c35f1d1e3/shapenet/data/mesh_vox.py#L138), instead of traditional 3x4...

I assume that Blender was set up with a custom camera model while doing rendering of Shapenet models? 
I really like and was planning on reusing your code written for `mesh_vox` module, but looks like in order to do this, I need a way of converting from classical 4x3 K into Blenders' 4x4 K... Or am I looking into a wrong direction here?

**Comment by gkioxari** [comment]
This is a great question. 
3D point transforms are represented with a 4x4 matrix. For example, see [`cameras`](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/cameras.py#L392) in PyTorch3D. There you will see how cameras, including the one you provide above which is a perspective camera

https://github.com/facebookresearch/pytorch3d/blob/e40c2167aef3785e896cccce582f47ef5439ebd5/pytorch3d/renderer/cameras.py#L714

The function that projects 3D world coordinates (converted to 4D homogeneous coordinates by appending 1.0) can be found here

https://github.com/facebookresearch/meshrcnn/blob/ab0762f87bfd4cbdf4560982c5c33832a445380b/shapenet/utils/coords.py#L159

This function basically converts the 3D coordinates from world to camera space by rectifying the frustrum as we show in Figure 4 in our paper.

**Comment by dmitrykudinov** [comment]
Got it, thank you. Closing for now.
