### ISSUE TITLE
batch_crop_voxels_within_box

### ISSUE THREAD

**Issue by ZZWENG** [facebookresearch/meshrcnn#58]
https://github.com/facebookresearch/meshrcnn/blob/master/meshrcnn/structures/voxel.py#L23

This line assumes that the voxels in an image have the same dimensions, as it's required by `torch.stack`. This is a very strong assumption.  I am working on a dataset where the voxels of the objects in an image can have different dimensions. For example, [N1, 3] and [N2, 3]. So this line would break the code. 

Also, the docstring of this function suggests that there is an unbatched version of this function, but I can't find it anywhere in the codebase. It may be helpful to add it.

**Comment by gkioxari** [comment]
The head of the network takes as input a `BxCxMxM` region and via a CNN it predicts `BxVxVxV` voxels. So the use case of equal sized voxels across examples in the batch is driven by the architecture of the network. The ground truth voxels can have whatever dimension they want to have as we store them (`VoxelInstances`) as a list of 3D points which are then converted into `VxVxV` voxels in [`verts2voxel`](https://github.com/facebookresearch/meshrcnn/blob/master/meshrcnn/structures/voxel.py#L116)

Yo are right that the `batch_crop_voxels_within_box` stacks the list of 3D points so it assumes they are equal  so you could instead use a for loop.

**Comment by ZZWENG** [comment]
Thank you. Does that mean if the ground truth objects in an image have different voxel sizes, then all I need to do is to adjust the `batch_crop_voxels_within_box` with a for loop, or use a batch size of 1?

**Comment by gkioxari** [comment]
All you need is create batches of the target destination size (which is determined by your network architecture). So all you have to do is adjust the code in `batch_crop_voxels_within_box` to do that which you can do with a for loop and without stacking which would give you an error.

**Comment by ZZWENG** [comment]
Thank you! It worked.
