### ISSUE TITLE
Is the release code the lighter version without residual architecture？

### ISSUE THREAD

**Issue by asurada404** [facebookresearch/meshrcnn#61]
Does the code following the architecture presented in Table 7(appendix  C)？
The mesh refinement branch has three stages, each with three graph Conv layers.
![image](https://user-images.githubusercontent.com/24955314/94115839-dc153a80-fe7c-11ea-9911-69948fbb3106.png)

**Comment by gkioxari** [comment]
Yes, it's the lighter version. We found that the residual connections did not add anything to performance, and made the model more complicated.

**Comment by asurada404** [comment]
OK, thanks for your reply :D
