### ISSUE TITLE
Shapenet's min-max constants?

### ISSUE THREAD

**Issue by dmitrykudinov** [facebookresearch/meshrcnn#62]
Hi @gkioxari ,

a quick question: how did you calculate 
```
SHAPENET_MIN_ZMIN = 0.67
SHAPENET_MAX_ZMAX = 0.92
```
in shapenet.utils.coords.py?

Is it by applying K.mm(RT) to the entire shapenet set and calculating extremes on verts[2]?

**Comment by gkioxari** [comment]
Honestly, I don't remember! They do come from the ShapeNet training set but I don't remember exactly how they are calculated. @jcjohnson might remember?

**Comment by dmitrykudinov** [comment]
Please never mind, I figured this out - indeed, these are extremums of `project_verts(<shapenet>, K.mm(RT))`. Closing.
