### ISSUE TITLE
Direction of Z axel in Voxel Head?

### ISSUE THREAD

**Issue by dmitrykudinov** [facebookresearch/meshrcnn#63]
Hi, @gkioxari ,

when training the voxel head, what is the direction of the Z axis - are the closest voxels to the camera are also closest to the voxel_head's features?, i.e.
![image](https://user-images.githubusercontent.com/3879467/94497114-0e8ba400-01ab-11eb-9500-79fcbc0f0db4.png)

or is it inverse? i.e.

![image](https://user-images.githubusercontent.com/3879467/94497168-3844cb00-01ab-11eb-8fcf-894d4204560e.png)

**Comment by gkioxari** [comment]
small Z means it's closer to the camera. Large Z means it's further.

**Comment by dmitrykudinov** [comment]
thank you, closing.
