### ISSUE TITLE
Vert-Align Question

### ISSUE THREAD

**Issue by sjcv** [facebookresearch/meshrcnn#67]
Not a bug in the code, but a question related to the MeshRCNN paper. Will be helpful if you can answer this. Thanks!

During the vert align step, you project each vertex onto image plane using camera's intrinsic matrix. How are you able to convert the mesh from world coordinates to camera coordinates without the Rotation and Translation values? Aren't these necessary?
`transform_meshes_to_camera_coord_system` 

How does the projected image has the same alignment as the input image without knowing the Rotation and Translation in the world system?

**Comment by gkioxari** [comment]
There is only one space, that's the `camera coordinate system` or `camera view system` basically the world with center the camera. 

The data, as released by Pix3D or ShapeNet, lives in a canonical space. With each instance/image there is a R, T that transforms the model from canonical space to camera view space. Mesh R-CNN does make any use nor does it care about the canonical space. We only see objects as they are in camera view space. And at prediction time, our predictions are in camera view space directly. Perhaps you are confused with other papers, that make predictions in canonical space. Mesh R-CNN does makes **predictions directly in camera view space**

**Comment by sjcv** [comment]
Thanks @gkioxari for the answer. I have a couple of follow up questions on the vert-align step. 

1. In the following comment, it is mentioned that the projection step is only needed if we want to predict in the world space. But since we are predicting in the camera space, are we not projecting the mesh?
https://github.com/facebookresearch/meshrcnn/blob/89b59e6df2eb09b8798eae16e204f75bb8dc92a7/shapenet/modeling/heads/mesh_head.py#L97


2. For vert-align step, there needs to be a normalisation performed on the verts coordinates as mentioned here. Where in the code are we doing this?
https://github.com/facebookresearch/meshrcnn/blob/89b59e6df2eb09b8798eae16e204f75bb8dc92a7/shapenet/modeling/heads/mesh_head.py#L97

Thanks for answering these.
