### ISSUE TITLE
GraphConv in which space?

### ISSUE THREAD

**Issue by dmitrykudinov** [facebookresearch/meshrcnn#70]
Hi @gkioxari ,

If I read it correctly, [the graph convolutions are applied](https://github.com/facebookresearch/meshrcnn/blob/89b59e6df2eb09b8798eae16e204f75bb8dc92a7/shapenet/modeling/heads/mesh_head.py#L100-L110) on geometry in the voxel space (except for z-scaling), whereas the [mesh head is trained to adjusts the vertices](https://github.com/facebookresearch/meshrcnn/blob/89b59e6df2eb09b8798eae16e204f75bb8dc92a7/shapenet/modeling/heads/mesh_head.py#L129) in the world space. I.e. the mesh head learns the [voxel_to_world ](https://github.com/facebookresearch/meshrcnn/blob/89b59e6df2eb09b8798eae16e204f75bb8dc92a7/shapenet/utils/coords.py#L60) translation through SGD. 

If the above conclusion is correct, did you consider using `meshes.verts_packed()` instead of `vert_pos_packed` in [gconvs](https://github.com/facebookresearch/meshrcnn/blob/89b59e6df2eb09b8798eae16e204f75bb8dc92a7/shapenet/modeling/heads/mesh_head.py#L117), and if so what was the reason behind choosing the latter option?

**Comment by gkioxari** [comment]
The graph convolutions take in as input features (sampled with the vert locations from the input feature maps) and `(x,y,z)` vertices for each node in the graph. The space in which the `(x,y,z)` features live in is the space after it is un-normalized by K (See Prediction Space in Figure 4 of the paper).  

 > If the above conclusion is correct, did you consider using meshes.verts_packed() instead of vert_pos_packed in gconvs, and if so what was the reason behind choosing the latter option?

This I don't quite understand. Can you clarify what you mean?

**Comment by dmitrykudinov** [comment]
My point was that the `meshes` [come to the MeshRefinementStage](https://github.com/facebookresearch/meshrcnn/blob/89b59e6df2eb09b8798eae16e204f75bb8dc92a7/shapenet/modeling/heads/mesh_head.py#L101) already in the **world space**. 

Then a copy of the mesh vertices goes through the K-projection to perform `vert_align`. 

And then, this K-projected copy of vertices is fed to the `gconvs` followed by fully-connected `vert_offset` generating offsets to modify the original meshes. But meshes are still in the world space, right? i.e. the mesh head is also learning an inverse K transformation to be able to match input xyz in K-projected space with the offsets in the world space, right?

**Comment by gkioxari** [comment]
Yes I think you are right!

**Comment by dmitrykudinov** [comment]
aha, thank you for reviewing and confirming. 
Hence was my original question about using `meshes.verts_packed()` instead of `vert_pos_packed` in gconvs. Since inverse K-projection is known, that would be one less thing to derive through SGD. We are going to try it on our data once ready, and I can let you know, if you are interested, if the proposed change makes any positive difference.

**Comment by dmitrykudinov** [comment]
Just a comment here for the folks working on practical applications, like @albertotono et al - the tanh activation on the mesh_head's stage, since the stage learns ndc to world space translation, be careful with world objects which are much bigger than [-1..+1]^3 NDC cube as this may lead to a numeric stability issue. A solution here can be mesh loss calculation in NDC space and transformation into the world space later at inference time, if needed.
