### ISSUE TITLE
Why assert num_workers equals 0 in preprocess

### ISSUE THREAD

**Issue by leoyejl** [facebookresearch/meshrcnn#71]
Hi, thank you for your excellent work. 

I'm confused that why the `num_workers` must be 0 when we sample points on mesh surface under the shapenet preprocess period.

```python
if args.num_samples > 0:
    assert args.num_workers == 0
```

https://github.com/facebookresearch/meshrcnn/blob/master/tools/preprocess_shapenet.py#L104

I want the code to be parallel, but I don’t know what effect this has on sampling points.

**Comment by gkioxari** [comment]
The preprocessing script indeed assumes a single worker. The reason for this is that we were too lazy to write something fancy and figure out how to aggregate samples from multiple workers etc. for a thing that needs to run once ever.
