### ISSUE TITLE
List for Holes Test Set

### ISSUE THREAD

**Issue by SteveJunGao** [facebookresearch/meshrcnn#72]
Hi,

Thanks for releasing the code! I'm wondering have you released or have any plan to release the list for Holes test set introduced in your paper?

Thanks,
Jun

**Comment by gkioxari** [comment]
You can find this here.

[non-simple.json.zip](https://github.com/facebookresearch/meshrcnn/files/5403315/non-simple.json.zip)

**Comment by SteveJunGao** [comment]
Thanks a lot for sharing!!!
