### ISSUE TITLE
FYI - Userwarning Messages : Userwarning-the-given-numpy-array-is-not-writeable / and others

### ISSUE THREAD

**Issue by albertotono** [facebookresearch/meshrcnn#77]
Before starting the training, it gave me these userwarning messages, not sure of their repercussions in the training and model. 

**NumPy array is not writeable, and PyTorch does not support non-writeable tensors**

```/home/alberto/Documents/MeshRCNN/meshrcnn/meshrcnn/data/meshrcnn_transforms.py:247: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) **NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor.** This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)```

It seems to be a broader issue with Pytorch
https://discuss.pytorch.org/t/userwarning-the-given-numpy-array-is-not-writeable/78748/3

I also received these. 
```
/home/alberto/Documents/MeshRCNN/meshrcnn/meshrcnn/structures/voxel.py:68:UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  item = item.nonzero()
/home/alberto/anaconda3/envs/meshrcnn/lib/python3.8/site-packages/detectron2/layers/wrappers.py:226: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  return x.nonzero().unbind(1)
/home/alberto/anaconda3/envs/meshrcnn/lib/python3.8/site-packages/torch/nn/functional.py:3118: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn("Default upsampling behavior when mode={} is changed "
/home/alberto/Documents/MeshRCNN/meshrcnn/meshrcnn/structures/voxel.py:68: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  item = item.nonzero()
```
Just checking

**Comment by gkioxari** [comment]
The latter is a PyTorch issue regarding the `nonzero()` op. It is annoying to see this warning! Hopefully the PyTorch team will fix this in a future release. 

I have never seen the former before. Not sure what this is about. Does training proceed normally?! If yes, ignore it :-D

**Comment by albertotono** [comment]
Thanks for checking in. and for the quick reply.  Yes, the "_training_" proceeded as expected ( "training" because I minimized everything to run on 1 gpu for testing with my 2 classes).  Now I am ready to move in multiGPUs in the cloud.
