### ISSUE TITLE
Vert-align steps

### ISSUE THREAD

**Issue by sjcv** [facebookresearch/meshrcnn#78]
With reference to #67 and #70, I have a couple of follow up questions on the vert-align step. 

1. In the following comment, it is mentioned that the projection step is only needed if we want to predict in the world space. But since we are predicting in the camera space, are we not projecting the mesh?
https://github.com/facebookresearch/meshrcnn/blob/89b59e6df2eb09b8798eae16e204f75bb8dc92a7/shapenet/modeling/heads/mesh_head.py#L97

2. For vert-align step, there needs to be a normalisation performed on the verts coordinates as mentioned here. Where in the code are we doing this?
https://github.com/facebookresearch/pytorch3d/blob/ae68a54f67a940d1e7b158b257df126817b94992/pytorch3d/ops/vert_align.py#L28-L32

Thanks for answering these.

**Comment by gkioxari** [comment]
See Figure 4 in our paper.
We unproject the points (using the camera matrix, or P in the code) in order to _undo_ the frustum which is not grid friendly.

**Comment by sjcv** [comment]
Thanks for clarifying. While in the voxel head, there are both the projection and unprojection steps; In the Mesh Head, I could not find the unprojection happening. Since vert-align requires projection of the mesh, shouldn't there be an unprojection step as well? Am I missing something?

**Comment by gkioxari** [comment]
The vertices are transformed with the camera matrix for the vert_align operation (so that pixel to feature alignment is preserved). The output meshes are in world space.

**Comment by sjcv** [comment]
Right, the vertices are projected for the vert-align step. Where is the unprojection happening? (Transformation from image plane to camera/world space). Is it not required for the input to the graphconv layer?

**Comment by gkioxari** [comment]
Sorry for the late response. Life is rather hectic right now 👎  

If I remember correctly, the projection step is used to align the vertices and the features in the vert_align step. This is so that the vertices pool features from the right location in the feature map grid (using K). That is the only part model that requires connecting 3D with 2D. The rest happens in world space.

**Comment by sjcv** [comment]
Thanks.
