### ISSUE TITLE
Is it possible to get the coordinates and angle of rotation of the detected object?

### ISSUE THREAD

**Issue by yujimori1967github** [facebookresearch/meshrcnn#79]
I listened to meshrcnn with great interest. I have a question.
Is it possible to get the coordinates and angle of rotation of the detected object?
Please tell me how to do it if possible.

**Comment by gkioxari** [comment]
The coordinates and angle of rotation of the object **with respect to what**? 
I think, and I might be wrong, that your question is tied to a canonical coordinate system for each object, e.g. the rotation of the detected chair with respect to a left facing chair. Mesh R-CNN predicts directly in camera view and makes no assumption about the existence of a canonical coordinate system.

**Comment by yujimori1967github** [comment]
thank you for your answer.
I understand the contents of the answer.
What I wanted to do was to replace (overwrite) a similar 3D model (obj or plg sofa model) from the object (sofa, etc.) in the monocular image. I want to try it.

We would appreciate it if you could provide us with any useful information.
Best regards

**Comment by gkioxari** [comment]
I am not sure of the details of your project and I unfortunately don't have the bandwidth to help out with your problem. Good luck!
