### ISSUE TITLE
Pre-processing Pix3D

### ISSUE THREAD

**Issue by nileshkulkarni** [facebookresearch/meshrcnn#8]
Hi,
It is possible to get the code that generated the `pix3d_s1_train.json` ` pix3d_s2_train.json` etc.
I'm curious about the K matrix, and how it was generated from the annotations provided with the pix3d dataset.

Thanks!

**Comment by gkioxari** [comment]
Hi @nileshkulkarni. This is a great question! So here it is! The `K` field in the json's contains `[f, px, py]`. Now, `f = f_pix3d * image_width / 32`, where `f_pix3d` is the focal length provided by the Pix3D dataset and is the "estimated focal length (in mm, and the width of the sensor is fixed to 32mm; used in rendering)" (see [here](https://github.com/xingyuansun/pix3d) for more), `px = image_width / 2` and `py = image_height / 2`

Now, if you load a model, rotate it with the rotation and translation matrices in the annotations, you should be able to project it back to the image plane with `K` as follows:
```
# camera coordinate system
x = f * verts[:, 0] / verts[:, 2] 
y = f * verts[:, 1] / verts[:, 2] 
# image coordinate system
x = -x + px
y = -y + py
# project to image plane 
new_img = np.zeros((image_width, image_height))
new_img[y, x] = 1
```
Now `new_img` should correspond to the mask of the object on the image plane!

**Comment by nileshkulkarni** [comment]
Hi @gkioxari. Thank you so much!

**Comment by AnuragSahu** [comment]
Thanks @gkioxari I was getting so much worried about the weirdly large values of f.
