### ISSUE TITLE
mesh_head stages: frequency filters / levels of detail 

### ISSUE THREAD

**Issue by dmitrykudinov** [facebookresearch/meshrcnn#81]
Hi @gkioxari ,

A rather conceptual question / idea. The three stages of the mesh head, in your implementation: all are passed the same number of points sampled from GT and predicted meshes. 

The idea is to treat the stages as individual frequency filters (from low to high) and feed accordingly a small - medium - large number of sampled points into stage1 - stage2 - stage3. We also assign dynamic (changing over # of iters) per-stage loss weights so first the stage1 is trained the most, then as its loss curve levels, the emphasis goes to stage2, and later - stage3.

Our early experiments show that training this way allows for Chamfer loss go lower and faster. Also, this appears to be more efficient from the GPU memory utilization standpoint, as allows for a higher level of detail to be communicated to stage3 by reducing the number of [points sampled](https://github.com/facebookresearch/meshrcnn/blob/d59029ee819bda32f00354af2e5fcdb2223d23fd/shapenet/modeling/heads/mesh_loss.py#L97) for stage1.

Is it something you considered before and decided not to pursue in your implementation? And if so, what was the reason?

**Comment by gkioxari** [comment]
Oh that makes a lot of sense! That's a nice result! We never thought of doing that but I think it's super reasonable!

**Comment by dmitrykudinov** [comment]
Good, thanks for giving this a thought. Closing.

**Comment by dmitrykudinov** [comment]
... and one can get to even better results if to represent the per-stage weights and # of sampled points per-stage as trainable params constrained by softmax
