### ISSUE TITLE
different `input_channels` in shapenet and pix3d impls

### ISSUE THREAD

**Issue by dmitrykudinov** [facebookresearch/meshrcnn#82]
Hi @gkioxari ,

if I read correctly, shapenet and pix3d implementations have different number of `input_channels` going into mesh_head's stage bottlenecks: [shapenet's summing the # of resnet50's output channels](https://github.com/facebookresearch/meshrcnn/blob/master/shapenet/modeling/mesh_arch.py#L34) whereas [pix3d's taking only the FPN's `p2` channel dimensionality](https://github.com/facebookresearch/meshrcnn/blob/master/meshrcnn/modeling/roi_heads/roi_heads.py#L118).

Can you tell what was the reason behind this difference?

**Comment by gkioxari** [comment]
In a way the ShapeNet and Pix3D models are different in the same way that a classification model is different from a detection model! 

The features that go into the mesh prediction head for the ShapeNet experiments are the ones res5 block feature maps. Note that our code supports the option of concatenating the features from all res blocks, hence the `sum(feat_dims)` but we all our models only contain the final feature map as we didn't see improvement from concatenating all of them. 

For the detection setting with Pix3D, the `in_channels` that you mention here are the feature dimensions which are the same for all levels, see [here](https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/roi_heads/roi_heads.py#L574-L579) for an explanation in detectron2. The input to RoIAlign comes from all levels (p2 to p5).

**Comment by dmitrykudinov** [comment]
Makes sense, closing. Thank you.
