### ISSUE TITLE
Volume estimation from 3D image

### ISSUE THREAD

**Issue by srivathsan-g** [facebookresearch/meshrcnn#83]
Hi,
I have a problem statement which has multiple similar (curved) objects in a 2D image and their volumes need to be estimated. Is it possible to do this using the trained model given in your repo or does it require any modifications specific to this problem? If yes, do point me in the right direction. Also, will I be required to use multiple views of the same objects for my problem? (It is possible for me to obtain multiple views for my use case)

Thanks in advance.

**Comment by gkioxari** [comment]
Your problem sounds exciting! However, I know very little about it to be able to offer any advice on how to go about it. I also don't have the bandwidth to help you. I am really sorry! Good luck!!
