### ISSUE TITLE
mean/std normalization in meshrcnn

### ISSUE THREAD

**Issue by dmitrykudinov** [facebookresearch/meshrcnn#84]
Hi @gkioxari ,

in [meshrcnn_transforms](https://github.com/facebookresearch/meshrcnn/blob/d59029ee819bda32f00354af2e5fcdb2223d23fd/meshrcnn/data/meshrcnn_transforms.py#L77) you are saying that "_mean/std normalization is done by the model instead of here_" - I assume in Detectron2 backbone? But I could not find the normalization logic neither in [Resnet](https://github.com/facebookresearch/detectron2/blob/v0.1.3/detectron2/modeling/backbone/resnet.py#L457) nor [FPN code](https://github.com/facebookresearch/detectron2/blob/v0.1.3/detectron2/modeling/backbone/fpn.py#L109)...
So where in the meshrcnn model code is the image normalization logic happening given the PIXEL_MEAN and PIXEL_STD cfg values?

thank you.

**Comment by gkioxari** [comment]
This is something that detectron2 takes care for me right here https://github.com/facebookresearch/detectron2/blob/d135f1d9bddf68d11804e09722f2d54c0672d96b/detectron2/modeling/meta_arch/rcnn.py#L223-L230

This is the whole logic of using detectron2. You don't need to bother with setting up the model (data preprocessing, backbone build) and you only worry about adding your part!

**Comment by dmitrykudinov** [comment]
Ah, the META_ARCHITECTURE, right! Thank you, closing.
