### ISSUE TITLE
Question on verts space inside MeshRefinementStage

### ISSUE THREAD

**Issue by dmitrykudinov** [facebookresearch/meshrcnn#87]
Hi @gkioxari ,

looking at the [vert_align](https://github.com/facebookresearch/meshrcnn/blob/master/meshrcnn/modeling/roi_heads/mesh_head.py#L173) of the MeshRefinementStage, given the doc for vert_align [saying](https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/ops/vert_align.html) 
"_(x, y) verts should be normalized such that (-1, -1) corresponds to top-left and (+1, +1) to bottom-right location in the input feature map._", I assume that the mesh coming into the MeshRefinementStage is still in the NDC space within the [-1..+1]^3 cube - is this correct?

**Comment by dmitrykudinov** [comment]
Never mind please, I figured this out. Closing.

**Comment by zhiwenfan** [comment]
Hi, 
I have one question with vert_align.py
When I print the max value of verts, I found that the max value is more than 1. But according to the author, the max and min value should be 1 and -1 respectively?
(Pdb) torch.max(verts)
tensor(21.8750, device='cuda:0')
Look forward to your reply!

**Comment by zhiwenfan** [comment]
Oh, seems that verts in vert_align.py is transposed by intrinsics.
