### ISSUE TITLE
Custom training of mesh refinement branch.

### ISSUE THREAD

**Issue by AstitvaSri** [facebookresearch/meshrcnn#91]
Hi, I want to train only the **Mesh Refinement Branch** with my own cubified meshes and ground truth meshes as training data. Is there a simple way to do that?

**Comment by gkioxari** [comment]
So you want to train a network that takes as input voxels and predicts meshes and you don't care about the rest of the network in mesh r-cnn (backbone CNN, object detector etc.)? In that case, you can write your own training loop with the model being only the mesh refinement branch and train it.

**Comment by AstitvaSri** [comment]
Mesh refinement stage requires "image features" from the backbone network. What should I pass there as I don't have any images?
