### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 1.72 GiB (GPU 0; 5.79 GiB total capacity; 2.37 GiB already allocated; 1.23 GiB free; 2.38 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by koeglfryderyk** [facebookresearch/meshrcnn#92]
I am trying to train meshrcnn on the Pix3D dataset on my machine with one Nvidia RTX 2060. I run the following command from the INSTRUCTIONS_PIX3D.md (I changed num-gpus to 1, because I only have one gpu):

`python tools/train_net.py --num-gpus 1 \
--config-file configs/pix3d/meshrcnn_R50_FPN.yaml`

Furthermore, I changed the BATCH_SIZE_PER_IMAGE in meshrcnn_R50_FPN.yaml to 1, but I still get the error

`RuntimeError: CUDA out of memory. Tried to allocate 1.72 GiB (GPU 0; 5.79 GiB total capacity; 2.37 GiB already allocated; 1.23 GiB free; 2.38 GiB reserved in total by PyTorch)`

Is my GPU simply not powerful enough, or is there something that I can change to make the training work?

I'd appreciate any help!

**Comment by gkioxari** [comment]
Your GPU seems to have total of 5.79GB total capacity. This is not enough.

**Comment by koeglfryderyk** [comment]
Ok, thank you. Could you tell me what the minimum capacity is?
