### ISSUE TITLE
Training with a custom dataset

### ISSUE THREAD

**Issue by koeglfryderyk** [facebookresearch/meshrcnn#93]
I want to train meshrcnn on my custom dataset. This dataset consists of pairs of images and masks and also the corresponding 3D model.

Maybe this is trivial (and the question is quite general) but I don't know how to approach this problem, so any help would be appreciated!

**Comment by gkioxari** [comment]
You will have to write your own data loader and bring the data to the same state as Pix3D. Check the data loader

https://github.com/facebookresearch/meshrcnn/blob/master/meshrcnn/data/datasets/pix3d.py

for more details

**Comment by grEmsIsY** [comment]
@koegl Have you done it yet? Can i have a look? Thank you!
